###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "bagi",
  "password": "test"
}

> {%
     client.global.set("auth_token", response.body.json.token); // this not work in my case...need to find out a solution or use POSTMAN
     var auth_token = client.global.get("auth_token");
     client.log(auth_token);
  %}

###
GET http://localhost:8080/hello
Authorization: Bearer {{auth_token}}

###